application: orbital-kit-125023
version: 1
runtime: python27
api_version: 1
threadsafe: true

# builtins:
# - remote_api: on

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static/css
  static_dir: static/css

- url: /static/js
  static_dir: static/js

- url: /static/img
  static_dir: static/img

- url: /static/fonts
  static_dir: static/fonts

# - url: /_ah/remote_api
#   script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
#   login: admin

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest